### ISSUE TITLE
AuthenticationEndpointContextListener Exception

### ISSUE THREAD

**Issue by azimhawaldar** [wso2-extensions/identity-outbound-auth-sms-otp#6]
Hi,

When I deploy the war file smsotpauthenticationendpoint.war in webapp folder, and start the server, I am getting below error. Can you help me what I doing wrong here? By the way, I am using WSO2 Identity Server 5.0.0

Thanks,
Azim

Error configuring application listener of class org.wso2.carbon.identity.application.authentication.endpoint.util.listener.AuthenticationEndpointContextListener {org.apache.catalina.core.StandardContext}
java.lang.ClassNotFoundException: org.wso2.carbon.identity.application.authentication.endpoint.util.listener.AuthenticationEndpointContextListener
	at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:138)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:280)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:177)
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWebappDeployment(TomcatGenericWebappsDeployer.java:222)
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWarWebappDeployment(TomcatGenericWebappsDeployer.java:174)
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleHotDeployment(TomcatGenericWebappsDeployer.java:141)
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.deploy(TomcatGenericWebappsDeployer.java:116)
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deployThisWebApp(AbstractWebappDeployer.java:140)
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deploy(AbstractWebappDeployer.java:90)
	at org.wso2.carbon.webapp.deployer.WebappDeployer.deploy(WebappDeployer.java:42)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.DeploymentEngine.loadServices(DeploymentEngine.java:135)
	at org.wso2.carbon.core.CarbonAxisConfigurator.loadServices(CarbonAxisConfigurator.java:464)
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:95)
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:398)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:219)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1267)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1186)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1081)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5027)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
TID: [0] [IS] [2016-08-04 12:23:55,683] ERROR {org.apache.catalina.core.StandardContext} -  Skipped installing application listeners due to previous error(s) {org.apache.catalina.core.StandardContext}
TID: [0] [IS] [2016-08-04 12:23:55,683] ERROR {org.apache.catalina.core.StandardContext} -  Error listenerStart {org.apache.catalina.core.StandardContext}
TID: [0] [IS] [2016-08-04 12:23:55,683] ERROR {org.apache.catalina.core.StandardContext} -  Context [/smsotpauthenticationendpoint] startup failed due to previous errors {org.apache.catalina.core.StandardContext}
TID: [0] [IS] [2016-08-04 12:23:56,167] ERROR {org.wso2.carbon.tomcat.internal.CarbonTomcat} -  Cannot stop context  {org.wso2.carbon.tomcat.internal.CarbonTomcat}
org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_stop]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/smsotpauthenticationendpoint]] in state [DESTROYED]

**Comment by hmrajas** [comment]
Did you get the war file from this[1] location?

[1][](http://product-dist.wso2.com/downloads/is-connectors/2.0.0/smsotp/other_artifacts.zip)

**Comment by azimhawaldar** [comment]
Hi ,

I did not got the jar from the URL you provided. I followed the steps I mean cloned the git hub project and using maven I build the war file. Do you need me to use the war provided in the above URL? Please let me know , waiting for your next reply.

Thanks,
Azim

**Comment by hmrajas** [comment]
Now you can use the war from store and for the solution please follow the jira[1].

[1]https://wso2.org/jira/browse/ISCONNECT-23

**Comment by azimhawaldar** [comment]
Hi,

Thanks for the info. However, after deploying the war file, the SMS OTP configuration is not visible under federated authenticators. Below are the steps I followed,

1) Pasted the jar org.wso2.carbon.extension.identity.authenticator.smsotp.connector-2.0.2-SNAPSHOT.jar inside WSO2_IS_HOME/repository/components/lib
2) Pasted the war smsotpauthenticationendpoint in repository\deployment\server\webapps
3) Restarted the server.

Please let me know, if I have missed something here.

Thanks,
Azim

**Comment by hmrajas** [comment]
Did you followed  step to Configuring the identityprovider[1].

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+SMSOTP+Authenticator#ConfiguringSMSOTPAuthenticator-Configuringtheidentityprovider

**Comment by azimhawaldar** [comment]
Hi,

Yes I did followed this. But I am not able to find SMSOTP Configuration under Federated Authenticators . This is the point where I have stuck, not able to proceed further.

Thanks,
Azim

**Comment by hmrajas** [comment]
1) Pasted the jar org.wso2.carbon.extension.identity.authenticator.smsotp.connector-2.0.2-SNAPSHOT.jar inside WSO2_IS_HOME/repository/components/dropins

this should goes here

**Comment by azimhawaldar** [comment]
Hi,

Thank you very much. Indeed, I nearly had brain fever just to enable this SMSOTP feature. I will be posting further if I have any other issues. 

Thanks,
Azim

**Comment by azimhawaldar** [comment]
Hi,

I Just completed the entire flow of using SMS OTP as mentioned in https://docs.wso2.com/display/ISCONNECTORS/Configuring+SMSOTP+Authenticator. This feature is for everty time user logins he has to provide the OTP. But my requirement is different. How to use this OTP feature to activate user account? I mean for the first time when user registers,his account will be locked and once he provides the OTP, his account will be unlocked, something like Self Sign up feature of WSO2 IS. https://docs.wso2.com/display/IS510/Self+Sign+Up+and+Account+Confirmation

Thanks,
Azim
